import { Fund, FundPerformance } from './interfaces';
import { FundDto } from '../fund/dto/fund.dto';

export const mockFunds: Fund[] = [
  {
    id: 'FUND001',
    name: 'Manulife Growth Fund',
    category: 'Equity',
    performance: 8.5,
    risk: 'High',
    minimumInvestment: 1000,
    managementFee: 1.5
  },
  {
    id: 'FUND002',
    name: 'Manulife Bond Fund',
    category: 'Fixed Income',
    performance: 4.2,
    risk: 'Low',
    minimumInvestment: 500,
    managementFee: 0.8
  },
  {
    id: 'FUND003',
    name: 'Manulife Balanced Fund',
    category: 'Multi Asset',
    performance: 6.8,
    risk: 'Medium',
    minimumInvestment: 750,
    managementFee: 1.2
  }
];

export const mockFundPerformances: FundPerformance[] = [
  { fundId: 'FUND001', period: '1M', return: 2.1 },
  { fundId: 'FUND001', period: '3M', return: 6.3 },
  { fundId: 'FUND001', period: '6M', return: 12.5 },
  { fundId: 'FUND001', period: '1Y', return: 8.5 },
  { fundId: 'FUND002', period: '1M', return: 0.8 },
  { fundId: 'FUND002', period: '3M', return: 2.1 },
  { fundId: 'FUND002', period: '6M', return: 3.8 },
  { fundId: 'FUND002', period: '1Y', return: 4.2 },
  { fundId: 'FUND003', period: '1M', return: 1.5 },
  { fundId: 'FUND003', period: '3M', return: 4.2 },
  { fundId: 'FUND003', period: '6M', return: 7.8 },
  { fundId: 'FUND003', period: '1Y', return: 6.8 }
];

export const mockFundList: FundDto[] = [
  {
    id: 'FUND001',
    fundName: 'Manulife Growth Fund',
    code: 'MGF001',
    unitPrice: 10.25,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.12,
    navChangePercent: 1.18,
    fundType: 'Equity',
    riskLevel: 'High',
    manager: 'Manulife',
    establishedDate: '2015-03-01',
    fundSize: 25.6,
    status: 'Active',
    custodian: 'HSBC',
    dividendType: 'Accumulation',
    investmentScope: 'Global Equities'
  },
  {
    id: 'FUND002',
    fundName: 'Manulife Bond Fund',
    code: 'MBF002',
    unitPrice: 8.50,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: -0.05,
    navChangePercent: -0.59,
    fundType: 'Fixed Income',
    riskLevel: 'Low',
    manager: 'Manulife',
    establishedDate: '2012-06-15',
    fundSize: 18.3,
    status: 'Active',
    custodian: 'Citi',
    dividendType: 'Distribution',
    investmentScope: 'Global Bonds'
  },
  {
    id: 'FUND003',
    fundName: 'Manulife Balanced Fund',
    code: 'MBF003',
    unitPrice: 9.80,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.08,
    navChangePercent: 0.82,
    fundType: 'Multi Asset',
    riskLevel: 'Medium',
    manager: 'Manulife',
    establishedDate: '2018-01-20',
    fundSize: 12.7,
    status: 'Active',
    custodian: 'HSBC',
    dividendType: 'Accumulation',
    investmentScope: 'Equities & Bonds'
  },
  {
    id: 'FUND004',
    fundName: 'Manulife Asia Equity',
    code: 'MAE004',
    unitPrice: 12.10,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.20,
    navChangePercent: 1.68,
    fundType: 'Equity',
    riskLevel: 'Medium',
    manager: 'Manulife',
    establishedDate: '2016-09-10',
    fundSize: 20.1,
    status: 'Active',
    custodian: 'Citi',
    dividendType: 'Distribution',
    investmentScope: 'Asia Equities'
  },
  {
    id: 'FUND005',
    fundName: 'Manulife Global Bond',
    code: 'MGB005',
    unitPrice: 7.95,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: -0.03,
    navChangePercent: -0.38,
    fundType: 'Fixed Income',
    riskLevel: 'Low',
    manager: 'Manulife',
    establishedDate: '2011-11-05',
    fundSize: 15.9,
    status: 'Active',
    custodian: 'HSBC',
    dividendType: 'Distribution',
    investmentScope: 'Global Bonds'
  },
  {
    id: 'FUND006',
    fundName: 'Manulife US Equity',
    code: 'MUE006',
    unitPrice: 15.60,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.25,
    navChangePercent: 1.63,
    fundType: 'Equity',
    riskLevel: 'High',
    manager: 'Manulife',
    establishedDate: '2017-04-18',
    fundSize: 22.4,
    status: 'Active',
    custodian: 'Citi',
    dividendType: 'Accumulation',
    investmentScope: 'US Equities'
  },
  {
    id: 'FUND007',
    fundName: 'Manulife China Fund',
    code: 'MCF007',
    unitPrice: 11.30,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.10,
    navChangePercent: 0.89,
    fundType: 'Equity',
    riskLevel: 'High',
    manager: 'Manulife',
    establishedDate: '2019-07-22',
    fundSize: 14.2,
    status: 'Active',
    custodian: 'HSBC',
    dividendType: 'Accumulation',
    investmentScope: 'China Equities'
  },
  {
    id: 'FUND008',
    fundName: 'Manulife Emerging Markets',
    code: 'MEM008',
    unitPrice: 13.40,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.18,
    navChangePercent: 1.36,
    fundType: 'Equity',
    riskLevel: 'High',
    manager: 'Manulife',
    establishedDate: '2014-02-28',
    fundSize: 19.8,
    status: 'Active',
    custodian: 'Citi',
    dividendType: 'Distribution',
    investmentScope: 'Emerging Markets'
  },
  {
    id: 'FUND009',
    fundName: 'Manulife Tech Fund',
    code: 'MTF009',
    unitPrice: 16.80,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.30,
    navChangePercent: 1.82,
    fundType: 'Equity',
    riskLevel: 'High',
    manager: 'Manulife',
    establishedDate: '2020-05-10',
    fundSize: 16.5,
    status: 'Active',
    custodian: 'HSBC',
    dividendType: 'Accumulation',
    investmentScope: 'Technology Sector'
  },
  {
    id: 'FUND010',
    fundName: 'Manulife Healthcare Fund',
    code: 'MHF010',
    unitPrice: 14.25,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.22,
    navChangePercent: 1.57,
    fundType: 'Equity',
    riskLevel: 'Medium',
    manager: 'Manulife',
    establishedDate: '2013-08-30',
    fundSize: 13.6,
    status: 'Active',
    custodian: 'Citi',
    dividendType: 'Distribution',
    investmentScope: 'Healthcare Sector'
  },
  {
    id: 'FUND011',
    fundName: 'Manulife ESG Fund',
    code: 'MESG011',
    unitPrice: 10.90,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.09,
    navChangePercent: 0.83,
    fundType: 'Equity',
    riskLevel: 'Medium',
    manager: 'Manulife',
    establishedDate: '2016-12-12',
    fundSize: 11.2,
    status: 'Active',
    custodian: 'HSBC',
    dividendType: 'Accumulation',
    investmentScope: 'ESG Investments'
  },
  {
    id: 'FUND012',
    fundName: 'Manulife Dividend Fund',
    code: 'MDF012',
    unitPrice: 9.60,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.07,
    navChangePercent: 0.73,
    fundType: 'Equity',
    riskLevel: 'Medium',
    manager: 'Manulife',
    establishedDate: '2010-10-01',
    fundSize: 10.8,
    status: 'Active',
    custodian: 'Citi',
    dividendType: 'Distribution',
    investmentScope: 'Dividend Stocks'
  },
  {
    id: 'FUND013',
    fundName: 'Manulife Money Market',
    code: 'MMM013',
    unitPrice: 6.50,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.01,
    navChangePercent: 0.15,
    fundType: 'Money Market',
    riskLevel: 'Low',
    manager: 'Manulife',
    establishedDate: '2012-02-14',
    fundSize: 8.3,
    status: 'Active',
    custodian: 'HSBC',
    dividendType: 'Accumulation',
    investmentScope: 'Short-term Instruments'
  },
  {
    id: 'FUND014',
    fundName: 'Manulife Pacific Fund',
    code: 'MPF014',
    unitPrice: 13.90,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.16,
    navChangePercent: 1.17,
    fundType: 'Equity',
    riskLevel: 'Medium',
    manager: 'Manulife',
    establishedDate: '2015-05-25',
    fundSize: 17.4,
    status: 'Active',
    custodian: 'Citi',
    dividendType: 'Distribution',
    investmentScope: 'Pacific Region'
  },
  {
    id: 'FUND015',
    fundName: 'Manulife Europe Fund',
    code: 'MEF015',
    unitPrice: 12.75,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.13,
    navChangePercent: 1.03,
    fundType: 'Equity',
    riskLevel: 'Medium',
    manager: 'Manulife',
    establishedDate: '2013-03-17',
    fundSize: 13.9,
    status: 'Active',
    custodian: 'HSBC',
    dividendType: 'Accumulation',
    investmentScope: 'Europe Region'
  },
  {
    id: 'FUND016',
    fundName: 'Manulife Japan Fund',
    code: 'MJF016',
    unitPrice: 11.80,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.11,
    navChangePercent: 0.94,
    fundType: 'Equity',
    riskLevel: 'Medium',
    manager: 'Manulife',
    establishedDate: '2018-09-09',
    fundSize: 12.1,
    status: 'Active',
    custodian: 'Citi',
    dividendType: 'Distribution',
    investmentScope: 'Japan Equities'
  },
  {
    id: 'FUND017',
    fundName: 'Manulife India Fund',
    code: 'MIF017',
    unitPrice: 10.40,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.14,
    navChangePercent: 1.36,
    fundType: 'Equity',
    riskLevel: 'High',
    manager: 'Manulife',
    establishedDate: '2017-11-11',
    fundSize: 10.5,
    status: 'Active',
    custodian: 'HSBC',
    dividendType: 'Accumulation',
    investmentScope: 'India Equities'
  },
  {
    id: 'FUND018',
    fundName: 'Manulife Real Estate',
    code: 'MRE018',
    unitPrice: 17.20,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.28,
    navChangePercent: 1.65,
    fundType: 'Real Estate',
    riskLevel: 'Medium',
    manager: 'Manulife',
    establishedDate: '2016-06-06',
    fundSize: 21.7,
    status: 'Active',
    custodian: 'Citi',
    dividendType: 'Distribution',
    investmentScope: 'Global Real Estate'
  },
  {
    id: 'FUND019',
    fundName: 'Manulife Infrastructure',
    code: 'MINF019',
    unitPrice: 15.10,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.21,
    navChangePercent: 1.41,
    fundType: 'Infrastructure',
    riskLevel: 'Medium',
    manager: 'Manulife',
    establishedDate: '2014-04-04',
    fundSize: 18.9,
    status: 'Active',
    custodian: 'HSBC',
    dividendType: 'Accumulation',
    investmentScope: 'Infrastructure Assets'
  },
  {
    id: 'FUND020',
    fundName: 'Manulife Global Opportunities',
    code: 'MGO020',
    unitPrice: 18.50,
    currencyCode: 'USD',
    priceDate: '2025-07-15',
    navChange: 0.35,
    navChangePercent: 1.93,
    fundType: 'Multi Asset',
    riskLevel: 'High',
    manager: 'Manulife',
    establishedDate: '2021-01-01',
    fundSize: 23.2,
    status: 'Active',
    custodian: 'Citi',
    dividendType: 'Distribution',
    investmentScope: 'Global Opportunities'
  }
];
